#!/usr/bin/env python3
"""Build edms_delete executable via cogex (same pattern as csv_extractor)."""

import os
import subprocess
import sys

HIDDEN_IMPORTS = [
    "edms_delete",
    "edms_delete.config",
    "edms_delete.runner",
    "edms_delete.state",
    "edms_delete.tracker",
    "edms_delete.delete_operations",
    "edms_delete.data_access",
    "edms_delete.paths",
    "edms_delete.utils.cdf_functions",
    "edms_delete.utils.time_utils",
    "edms_delete.utils.logging_setup",
]

SPEC_TEMPLATE = """
# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by build_exe.py

import os
import sys

try:
    from edms_delete import __version__
    version = f"{{__version__}}-"
except ImportError:
    version = ""

if os.name == "nt":
    script_path = "edms_delete\\\\__main__.py"
else:
    script_path = "edms_delete/__main__.py"

a = Analysis(
    [script_path],
    pathex=[os.path.join(os.getcwd(), 'edms_delete')],
    binaries=[],
    datas=[],
    hiddenimports={hidden_imports},
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name=f"edms_delete-{{version}}{{sys.platform}}",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
)
"""


def generate_spec_file() -> str:
    spec_content = SPEC_TEMPLATE.format(hidden_imports=HIDDEN_IMPORTS)
    spec_path = "edms_delete.spec"
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)
    print(f"Generated {spec_path} with {len(HIDDEN_IMPORTS)} hidden imports")
    return spec_path


def build() -> None:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)
    spec_path = generate_spec_file()
    cmd = ["poetry", "run", "cogex", "build", "--spec", spec_path]
    print("Building:", " ".join(cmd))
    result = subprocess.run(cmd, shell=(os.name == "nt"))
    if result.returncode != 0:
        sys.exit(1)
    print("Build successful. Check dist/")


if __name__ == "__main__":
    build()
